name: s3_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - eumdac=0.17.0
  - cartopy=0.23.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - shapely=2.0.6
  - rasterio=1.3.10
  - xarray=2024.9.0
  - netcdf4=1.7.1
  - h5netcdf=1.3.0
  - scipy=1.13.1
  - gdal=3.9.2
  - geopandas=1.0.1
  - google-cloud-storage=2.18.2
  - lxml=5.3.0
  - pip
  - pip:
      - requests>=2.32.3
      - python-dotenv>=1.0.1
      - earthengine-api>=0.1.366